name: CI-Polaris
on:
  push:
    branches: [ main, develop, stage ]
  pull_request:
    branches: [ polaris ]


jobs:
  build:
    runs-on: [ubuntu-latest]
    timeout-minutes: 21
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Bridge 
        uses: blackduck-inc/black-duck-security-scan@main
        with:
         
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          include_diagnostics: true
          polaris_assessment_types: "SCA"
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when polaris_upload_sarif_report is set as true
