name: CI-Polaris
on:
  push:
    branches: [ main, develop, stage ]
  pull_request:
    branches: [ polaris ]


jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Bridge Bundle --> NON AIRGAP
        uses: blackduck-inc/black-duck-security-scan@SIGINT-2368
        with:
          enable_bridge_thin_client: false
          ### SCANNING: Required fields
          bridgecli_download_url: 'https://repo.blackduck.com/bds-integrations-release/com/blackduck/integration/bridge/binaries/bridge-cli-bundle/latest/bridge-cli-bundle-macos_arm.zip'
          #bridgecli_download_version: 3.5.0
          #bridgecli_install_directory: '/Users/kirann/bridge-cli-bundle'   
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          include_diagnostics: true
          polaris_assessment_types: "SAST"
          network_airgap: false
          #polaris_workflow_version: '3.0.42'
          #bridge_register_url: 'https://repo.blackduck.com/bds-integrations-release/com/blackduck/integration/bridge/package-manager/registries/registry.json'
          #polaris_prComment_enabled: true 
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when polaris_upload_sarif_report is set as true
      
